### PR TITLE
one TODO less in the code, also found and fixed a related bug

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
i have also made the call to enumerate in the same way as seen at a related place, giving the start number.

also made error msg when inputting a wrong choice more precise.

### CODE REVIEW

**Comment by kuba** [comment]
Since you've already made an effort to go through the code, do you think you would be able to write a small unit tests that would catch this bug? :)

**Comment by jdkasten** [comment]
I have completely rewritten this file... I will write the testcases.

**Comment by kuba** [comment]
Okay, thanks guys

**Comment by jdkasten** [comment]
This problem has subsequently been fixed. Thanks!

**Pull request closed without merging**
