### PR TITLE
Work in progress: IIS Configurator

### PR DESCRIPTION
**Pull request by felixrieseberg**
This isn’t actually a finished configurator, but a submodule link to the repo where the IIS development happens. 

If you’re interested in helping out, please reach out to me (feriese@microsoft.com) - I’m happy about any volunteer help I can get!

### CODE REVIEW

**Comment by pde** [comment]
Hi Felix!  I find submodules to be a cause of extra complexity and inconvenience.  Sometimes they're a necessary evil, but in this case couldn't we just merge your entire repo into the main client one?

**Comment by felixrieseberg** [comment]
*Absolutely*

**Comment by kuba** [comment]
Instead of git submodule or merging into the core I would like to suggest creating new Python package (`letsencrypt-iis`) and hooking it to the core using plugin architecture (based on setuptools entry points) as described in:
- http://letsencrypt.readthedocs.org/en/latest/plugins.html
- https://github.com/letsencrypt/lets-encrypt-preview/tree/master/examples/plugins
- #358

I would be more than happy to send an appropriate PR to your repo, @felixrieseberg :)

BTW @natemrice is currently working on https://github.com/natemrice/letsencrypt-powershell. You probably should be joining forces!

**Comment by felixrieseberg** [comment]
@kuba: Just to make sure that I'm not confused - when some of us met two weeks ago, we assumed that going with the interfaces spec and building `client/plugins/iis` using the authenticator and installer interface would be the way to go. If you're currently changing the plugin infrastructure and moving things around, we should probably pause our engagement until you guys have the interface down?

However, if you're able to send me a small magic PR and we can continue to code against the interface methods, then we're good :+1: 

(we're in touch with @natemrice, but thanks for the pointer)

**Comment by kuba** [comment]
Please excuse me for confusion - I was unaware of such discussion (most likely because I'm just a volunteer contributor, not strictly on the team).

While I'm pushing towards separate distribution of plugins (#358, hence above proposal for having `letsencrypt-iis`), interfaces/API are kept the same. You can have a look at the https://github.com/felixrieseberg/lets-encrypt-iis/pull/1 to see what I meant.

Nevertheless @jdkasten is in charge here, and it seems he would rather see IIS plugin merged in the core: https://github.com/letsencrypt/lets-encrypt-preview/pull/376#issuecomment-99351824

**Pull request closed without merging**
