### PR TITLE
dialog display on squeeze (fixes #280)

### LINKED ISSUE #280: Squeeze unable to run letsencrypt; constantly stymied by dialog.UnableToRetrieveBackendVersion
I think this relates to the closed issue discussing a reduction (and/or dropping) of support for python dialog.  Either way, this problem is a bit odd -- letsencrypt certainly runs, but it drops the dialog version to stdout and dies.  It feels like a solveable bug and not an insurmountable melding of minds.

```
Using /usr/lib/python2.6/dist-packages
Finished processing dependencies for letsencrypt==0.1
root@vpn4:~/lets-encrypt-preview# letsencrypt
Version: 1.1-20100428
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/usr/local/lib/python2.6/dist-packages/letsencrypt-0.1-py2.6.egg/letsencrypt/scripts/main.py", line 117, in main
    logger.addHandler(log.DialogHandler())
  File "/usr/local/lib/python2.6/dist-packages/letsencrypt-0.1-py2.6.egg/letsencrypt/client/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/usr/local/lib/python2.6/dist-packages/python2_pythondialog-3.0.1-py2.6.egg/dialog.py", line 1366, in __init__
    self.backend_version())
  File "/usr/local/lib/python2.6/dist-packages/python2_pythondialog-3.0.1-py2.6.egg/dialog.py", line 2028, in backend_version
    "{1!r}".format(self._dialog_prg, output))
dialog.UnableToRetrieveBackendVersion
root@vpn4:~/lets-encrypt-preview# dialog
cdialog (ComeOn Dialog!) version 1.1-20100428
Copyright 2000-2007,2008 Thomas E. Dickey
```

### PR DESCRIPTION
**Pull request by kuba**
@jdkasten, @pavgup does this work for you?

### CODE REVIEW

**Comment by pavgup** [comment]
Slightly slammed by the real world, but I'll test in the next couple days and report back.  Thanks!

**Comment by kuba** [comment]
Updated docs. I think this can be safely merged now and any other incompatibilities with squeeze should be considered in follow-up issues/PRs. BTW, in the meantime, dialog got updated to 3.2.2 final.

**Comment by kuba** [comment]
FYI it seems that fail is due to the Travis build runner

**Comment by jdkasten** [comment]
Thanks @kuba!

**Pull request merged**
