### PR TITLE
Fresh Detail in the using.rst file, but maybe meh

### PR DESCRIPTION
**Pull request by pavgup**
So, I'm intentionally offering this a bit haphazardly.  I had intended to update the travis.yml file, but I'm starting to wonder if the paradigm that's being used to build this may be a bit outside the norm.  Perhaps the goal shouldn't be to use the system utilities to find success, but rather to embrace the tools that already purport to do that.  My altered docs might not be that helpful if the goal is to seek simplicity and conformity -- but I thought, at least, it would provide a way for someone struggling to find some help.

And just so it's not lost, I'm advocating the CI file be significantly changed and perhaps not connected directly to the docs you might have users, with a penchant for risk naturally, who might stumble into a bit of a trap.

### CODE REVIEW

**Comment by pavgup** [comment]
Also, I should say there may be extraneous packages being installed by the strategies I proposed.  This is not yet "optimized" to be fair.

**Comment by kuba** [comment]
Thanks for the PR. However, one should NEVER ever mix up system Python packages with anything coming from outside the repositories. That is being said, **`sudo pip` is wrong** :(.

Sorry for my brevity. I'm extremely busy this week, and will be able to fully follow up next week...

**Comment by pavgup** [comment]
No rush, this was just a quick poke from my side as I was debating those docs.  To be clear, it is definitely rough -- just quick notes from my side -- (sudo pip included, oops), but it didn't make sense to hold this stuff privately.  Take your time responding.

**Comment by kuba** [comment]
This PR is redundant as of #313 and should be closed

**Pull request closed without merging**
