### PR TITLE
client.network2

### PR DESCRIPTION
**Pull request by kuba**
it should help to get you started, @garrettr :)

`python examples/restified.py`

### CODE REVIEW

**Comment by kuba** [comment]
I have merged this with `master` now

**Comment by jdkasten** [comment]
Squashing some of these commits seems necessary there are (70 of them over the course of a day)

**Comment by kuba** [comment]
Note that the list of commits above includes commits merged from master, so there aren't that many (please try to merge `master` with `hackathon` first, list should get shorter, likewise PR size). Squashing == history rewriting, and we both have experienced problems arising from that...

**Comment by jdkasten** [comment]
I have *not* experienced problems with "history rewriting" (other than receiving complaints from you :))

**Comment by kuba** [comment]
I will close this PR for now and send a real one diffed against `master` when it gets 100% coverage and full pylint compliance.

Updates are constantly being pushed to https://github.com/kuba/lets-encrypt-preview/tree/network2, just `git merge github.com/kuba/network` whenever necessary. You can also view a handy diff at https://github.com/letsencrypt/lets-encrypt-preview/compare/master...kuba:network2

**Pull request closed without merging**
