### PR TITLE
Rename the nginx ssl config file to match the final filename

### PR DESCRIPTION
**Pull request by fmarier**
This config file will ultimately exist as /etc/letsencrypt/options-ssl-nginx.conf
so we may as well use the right filename everywhere.

This is much easier to deal with in the Debian packaging.

### CODE REVIEW

**Comment by kuba** [comment]
Please update `MANIFEST.in`.

What about renaming `options-ssl.conf` to `options-ssl-apache.conf`?

**Comment by fmarier** [comment]
I've updated `MANIFEST.in`. Given the title of this PR, I guess I shouldn't change the apache filename ;)

I've put that in a follow-up PR.

**Comment by fmarier** [comment]
Follow-up PR in #484.

**Comment by kuba** [comment]
Thanks, LGTM :+1:

**Pull request merged**
