### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by kuba**
nitpick PR :)

### CODE REVIEW

**Comment by kuba** [comment]
@ThomasWaldmann you're absolutely right, I changed the output slightly and forgot to mention: good catch! @jdkasten, are you fine with new output?

**Comment by ThomasWaldmann** [comment]
The point was not picking on the changed output, but pointing out that if the different output is ok, the code can even be simpler than you have right now.

**Comment by kuba** [comment]
Sorry, I didn't spot the second part of your comment earlier, but I agree with you. "Fixed" in 61b87c0

**Comment by kuba** [comment]
FYI merged with current `master`

**Comment by jdkasten** [comment]
Thanks @schoen, I will take care of these in the cleanup branch before I merge it.

**Comment by jdkasten** [comment]
Merged in relevant commits Thanks!

**Pull request closed without merging**
