### PR TITLE
Pin pylint to 1.4.2 to workaround #289

### PR DESCRIPTION
**Pull request by garrettr**

### CODE REVIEW

**Comment by kuba** [comment]
LGTM, but it's important that we get back to `pylint>=1.4.0` later on, so maybe you could put this exact statement next to `upstream #248` comment for reference? thanks

**Comment by jdkasten** [comment]
ouch... something else must have changed...

**Comment by kuba** [comment]
AFAIR `astroid==1.3.5` + `pylint==1.4.2.` should work. It might also work with `astroid==1.3.5` + `pylint>=1.4.0`...

**Comment by jdkasten** [comment]
Thanks!

**Pull request merged**
